import type { Metadata } from 'next'
import MarketingNav from '@/components/marketing/MarketingNav'
import MarketingFooter from '@/components/marketing/MarketingFooter'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'The terms that govern your use of TrackDelta AI.',
}

const LAST_UPDATED = 'July 14, 2026'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-delta-950">
      <MarketingNav />

      <main className="max-w-3xl mx-auto px-6 py-20">
        <p className="text-delta-500 text-xs font-semibold uppercase tracking-widest mb-3">Legal</p>
        <h1 className="text-4xl font-bold text-white mb-3 tracking-tight">Terms of Service</h1>
        <p className="text-delta-500 text-sm mb-12">Last updated: {LAST_UPDATED}</p>

        <div className="space-y-10 text-delta-300 text-sm leading-relaxed">
          <Section title="1. Acceptance of terms">
            <p>
              By creating an account or using TrackDelta AI (&ldquo;TrackDelta,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;), you agree to
              these Terms of Service. If you do not agree, do not use the service.
            </p>
          </Section>

          <Section title="2. What TrackDelta does">
            <p>
              TrackDelta analyzes iRacing telemetry (.ibt) files you upload and generates coaching
              feedback — including a &ldquo;Driver DNA&rdquo; profile and session debriefs — based on
              patterns in your own driving data. Coaching output is generated by a combination of
              deterministic analysis and an AI language model, and is provided for informational and
              training purposes only. It is not a guarantee of lap time improvement, race results, or
              driving safety, and should not be treated as a substitute for your own judgment or
              professional instruction.
            </p>
          </Section>

          <Section title="3. Your account">
            <p>
              You&apos;re responsible for maintaining the security of your account credentials and for
              all activity that occurs under your account. You must provide accurate information when
              registering and keep it up to date.
            </p>
          </Section>

          <Section title="4. Subscriptions and billing">
            <p>
              TrackDelta offers a free tier with a limited number of session uploads per month, and a
              paid Pro subscription billed monthly through Stripe. By subscribing to Pro, you authorize
              us to charge your payment method on a recurring basis until you cancel. You can cancel at
              any time from your billing page — access continues until the end of the current billing
              period, and no further charges will be made. We do not store your payment card details;
              they are handled directly by Stripe.
            </p>
          </Section>

          <Section title="5. Your content">
            <p>
              You retain all rights to the telemetry files and data you upload. By uploading a session,
              you grant TrackDelta a limited license to process, store, and analyze that data solely to
              provide the service to you (generating your Driver DNA and coaching debriefs). We do not
              sell your telemetry data or share it with other users without your explicit consent.
            </p>
          </Section>

          <Section title="6. Acceptable use">
            <p>You agree not to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>Upload files that aren&apos;t your own iRacing telemetry, or that you don&apos;t have the right to upload</li>
              <li>Attempt to circumvent usage limits, billing, or access controls</li>
              <li>Use the service to build a competing product by scraping or reverse-engineering it</li>
              <li>Interfere with the normal operation of the service or other users&apos; access to it</li>
            </ul>
          </Section>

          <Section title="7. Disclaimers">
            <p>
              TrackDelta is provided &ldquo;as is&rdquo; without warranties of any kind, express or
              implied. Coaching feedback is generated from the data you provide and may be incomplete,
              delayed, or occasionally wrong — always use your own judgment. We are not liable for any
              driving decisions made based on TrackDelta&apos;s output, on-track or otherwise.
            </p>
          </Section>

          <Section title="8. Limitation of liability">
            <p>
              To the maximum extent permitted by law, TrackDelta and its operators are not liable for
              any indirect, incidental, or consequential damages arising from your use of the service.
              Our total liability for any claim relating to the service is limited to the amount you
              paid us in the twelve months preceding the claim.
            </p>
          </Section>

          <Section title="9. Termination">
            <p>
              You may stop using TrackDelta and delete your account at any time. We may suspend or
              terminate accounts that violate these terms, including abusive use of the free tier or
              non-payment on Pro subscriptions.
            </p>
          </Section>

          <Section title="10. Changes to these terms">
            <p>
              We may update these terms from time to time. If we make material changes, we&apos;ll
              notify you by email or through the app before they take effect.
            </p>
          </Section>

          <Section title="11. Contact">
            <p>
              Questions about these terms? Email us at{' '}
              <a href="mailto:hello@trackdeltaai.com" className="text-delta-400 hover:text-white transition-colors">
                hello@trackdeltaai.com
              </a>
              .
            </p>
          </Section>
        </div>
      </main>

      <MarketingFooter />
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-white font-semibold text-base mb-3">{title}</h2>
      {children}
    </section>
  )
}
